apiVersion: v1

kind: Service

metadata:
    name: myfrontend-service
    
spec:
    type: NodePort
    ports:
          - targetPort: 80
            port: 80
            nodePort: 30006

    selector:
        app: my-frontend
        type: frontend
